### ISSUE TITLE
Problems with giving/removing vehicles

### ISSUE THREAD

**Issue by GioPera06** [SBDPlugins/VehiclesPlus#134]
I always have a problem with this plugin, that when I use it for roleplay servers I have to remove and hand the vehicles to the police, so with this feature request I would propose the addition of a permit such as vp.garage.police that allows you to find the police vehicle in the garage

**Comment by stijnb1234** [comment]
So the feature you are requesting is looking into the garages of others and removing vehicles from it?

**Comment by GioPera06** [comment]
not really, a permission that if guaranteed to a group or a user let them use and have in the garage a specific car, and when they no longer have the permission they can't no longer see the car and use it

**Comment by stijnb1234** [comment]
I will not fully implement this, because it's pretty unrealistic that there is always a vehicle read to spawn from a garage. If you really want that, you need to do that yourself using the API.

But, the new garage recode for the v3 will make it possible to make a garage for specific people or people with a permission so that they can spawn the vehicles in that garage. You can then make a police garage containing vehicles for the police.
